import { useEffect, useState } from "react";
import { Bot, Send, ShieldCheck, Sparkles, X } from "lucide-react";
import { api } from "../lib/api";
import { ASTRA_MODELS } from "./Pages";

export default function AstraDrawer({open,onClose,enabled,model,setModel,context}){
 const [input,setInput]=useState("");const [messages,setMessages]=useState([]);const [busy,setBusy]=useState(false);
 useEffect(()=>{if(open&&context)setInput(`About this: ${context}\n\n`);},[open,context]);
 async function send(){const value=input.trim();if(!value||busy||!enabled)return;const next=[...messages,{role:"user",parts:[{text:value}]}];setMessages(next);setInput("");setBusy(true);try{const r=await api.chat(model,next);setMessages(m=>[...m,{role:"assistant",parts:[{text:r.text||"Astra couldn't generate a response."}]}]);}catch(e){setMessages(m=>[...m,{role:"assistant",parts:[{text:e?.message||"Astra could not complete that request."}]}]);}finally{setBusy(false)}}
 return <>{open&&<button aria-label="Close Astra" onClick={onClose} className="fixed inset-0 z-40 bg-black/35 backdrop-blur-[2px]"/>}<aside className={`astra-drawer ${open?"astra-drawer-open":""}`}><div className="flex items-center justify-between p-5 border-b border-white/[.06]"><div className="flex items-center gap-3"><div className="astra-mark"><Bot size={18}/></div><div><div className="font-semibold">Astra</div><div className="text-[10px] text-white/30">Aurora Cloud · Anvaya · by hash</div></div></div><button onClick={onClose} className="icon-btn"><X size={17}/></button></div>{!enabled?<div className="p-6 flex-1 grid place-items-center text-center"><div><ShieldCheck size={30} className="mx-auto text-white/25"/><h3 className="mt-4 font-medium">Astra is off</h3><p className="text-xs text-white/35 mt-2 leading-5">Turn Astra on in Settings when you want cloud AI.</p></div></div>:<><div className="p-4 border-b border-white/[.05]"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.16em] text-white/25">Model</span><span className="text-[10px] text-emerald-300">ready</span></div><select value={model} onChange={e=>setModel(e.target.value)} className="mt-2 w-full bg-[#1b0b14] border border-white/[.07] rounded-xl px-3 py-2.5 text-xs"><optgroup label="Antigravity">{ASTRA_MODELS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</optgroup></select></div><div className="flex-1 overflow-auto scrollbar p-4 space-y-3">{messages.length===0&&<div className="rounded-2xl bg-white/[.025] border border-white/[.05] p-4 text-xs text-white/35 leading-5"><Sparkles size={15} className="text-aurora-300 mb-2"/>Ask Astra to summarize a chat, plan a trip, draft something, explain a document, or help organize your Anvaya life.</div>}{messages.map((m,i)=><div key={i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-3.5 py-3 text-xs leading-5 ${m.role==="user"?"bg-[#752743]":"bg-white/[.045] border border-white/[.06]"}`}>{m.parts?.[0]?.text}</div></div>)}{busy&&<div className="text-xs text-white/30">Astra is thinking…</div>}</div><div className="p-4 border-t border-white/[.06]"><div className="astra-input flex items-end gap-2"><textarea rows="2" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask Astra…"/><button disabled={!input.trim()||busy} onClick={send} className="h-9 w-9 rounded-xl bg-aurora-600 grid place-items-center disabled:opacity-30"><Send size={16}/></button></div><div className="mt-2 flex items-center gap-1.5 text-[9px] text-white/20"><Sparkles size={11}/> Optional cloud AI · your choice</div></div></>}</aside></>
}
