import { useEffect, useState } from "react";
import { Search, UserPlus, Send, Check, ArrowLeft, ShieldCheck, MessageCircle, X } from "lucide-react";
import { supabase } from "../lib/supabase";

async function avatarUrl(path){
  if(!path||!supabase)return null;
  if(path.startsWith("http"))return path;
  const {data}=await supabase.storage.from("vyara-avatars").createSignedUrl(path,3600);
  return data?.signedUrl||null;
}
export default function Connect({user,onBack}){
 const derived=(user?.user_metadata?.username||user?.email?.split("@")[0]||"").toLowerCase().replace(/^@/,"").replace(/\s+/g,"");
 const [username,setUsername]=useState(""); const [result,setResult]=useState(null); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false); const [incoming,setIncoming]=useState([]);
 useEffect(()=>{if(derived&&!username)setUsername(derived); ensureProfile(); loadIncoming()},[user?.id,derived]);
 async function ensureProfile(){if(!supabase||!user?.id)return;await supabase.from("profiles").upsert({user_id:user.id,username:derived,display_name:user.user_metadata?.display_name||derived},{onConflict:"user_id"})}
 async function loadIncoming(){if(!supabase||!user?.id)return;const {data,error}=await supabase.from("friend_requests").select("id,sender_id,created_at").eq("receiver_id",user.id).eq("status","pending").order("created_at",{ascending:false});if(error){setStatus(error.message);return}const ids=(data||[]).map(r=>r.sender_id);let profiles=[];if(ids.length){const q=await supabase.from("profiles").select("user_id,display_name,username,avatar_url").in("user_id",ids);profiles=q.data||[]}const rows=await Promise.all((data||[]).map(async r=>{const p=profiles.find(x=>x.user_id===r.sender_id)||{};return {...r,profiles:p,avatar_url:await avatarUrl(p.avatar_url)}}));setIncoming(rows)}
 async function searchUser(e){e?.preventDefault();setBusy(true);setStatus("");setResult(null);const clean=username.trim().toLowerCase().replace(/^@/,"").replace(/\s+/g,"");try{const {data,error}=await supabase.from("profiles").select("id,user_id,username,display_name,avatar_url").eq("username",clean).maybeSingle();if(error)throw error;if(!data)setStatus("No Anvaya user found with that username.");else if(data.user_id===user.id)setStatus("That's your own Anvaya username.");else setResult({...data,avatar_url:await avatarUrl(data.avatar_url)})}catch(e){setStatus(e?.message||"Could not search profiles.")}finally{setBusy(false)}}
 async function sendRequest(){if(!result)return;setBusy(true);setStatus("");try{const {error}=await supabase.from("friend_requests").insert({sender_id:user.id,receiver_id:result.user_id,status:"pending"});if(error)throw error;setStatus("Request sent. They can accept it from Find People.")}catch(e){setStatus(e?.code==="23505"?"A request already exists.":e?.message||"Could not send request.")}finally{setBusy(false)}}
 async function accept(id){setBusy(true);setStatus("");try{const req=(incoming||[]).find(x=>x.id===id);if(!req?.sender_id)throw new Error("Connection request could not be found.");const {error:updateError}=await supabase.from("friend_requests").update({status:"accepted"}).eq("id",id).eq("receiver_id",user.id);if(updateError)throw updateError;const {data:conversationId,error:rpcError}=await supabase.rpc("get_or_create_direct_conversation",{p_other_user:req.sender_id});if(rpcError)throw rpcError;if(!conversationId)throw new Error("Connection was accepted, but the conversation could not be created.");setStatus("Connection accepted. Your private chat is ready.");await loadIncoming()}catch(e){setStatus(e?.message||"Could not accept the connection.")}finally{setBusy(false)}}
 return <div className="h-full overflow-auto scrollbar p-7"><div className="max-w-4xl mx-auto"><button onClick={onBack} className="icon-btn mb-7"><ArrowLeft size={17}/></button><div className="flex items-end justify-between gap-4"><div><div className="text-2xl font-semibold">Find people</div><p className="text-sm text-white/35 mt-1">Search a Anvaya username. No phone numbers required.</p></div><div className="hidden sm:block text-right"><div className="text-[10px] uppercase tracking-[.16em] text-white/20">Your Anvaya ID</div><div className="text-sm font-medium mt-1">@{derived}</div></div></div>
 <div className="mt-6 glass rounded-3xl p-5"><form onSubmit={searchUser} className="flex gap-2"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-white/25"/><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username" className="w-full bg-white/[.03] border border-white/[.07] rounded-xl pl-10 pr-3 py-3 text-sm"/></div><button className="btn-primary" disabled={busy}>{busy?"Searching…":"Search"}</button></form>{result&&<div className="mt-4 rounded-2xl bg-white/[.035] border border-white/[.06] p-4 flex items-center gap-4"><Avatar profile={result}/><div className="flex-1"><div className="font-medium">{result.display_name||result.username}</div><div className="text-xs text-white/35">@{result.username}</div></div><button onClick={sendRequest} disabled={busy} className="btn-primary flex items-center gap-2"><UserPlus size={16}/> Connect</button></div>}{status&&<div className="mt-4 text-xs text-white/45 bg-white/[.03] border border-white/[.05] rounded-xl p-3">{status}</div>}</div>
 {incoming.length>0&&<div className="mt-6 glass rounded-3xl p-5"><div className="flex items-center gap-2 mb-4"><UserPlus size={16} className="text-aurora-300"/><span className="text-sm font-medium">Connection requests</span></div>{incoming.map(r=><div key={r.id} className="flex items-center gap-3 py-3 border-b border-white/[.04] last:border-0"><Avatar profile={{...r.profiles,avatar_url:r.avatar_url}}/><div className="flex-1"><div className="text-sm font-medium">{r.profiles?.display_name||r.profiles?.username}</div><div className="text-xs text-white/35">@{r.profiles?.username}</div></div><button onClick={()=>accept(r.id)} disabled={busy} className="btn-primary flex items-center gap-2"><Check size={15}/> Accept</button></div>)}</div>}
 <div className="mt-8 grid sm:grid-cols-3 gap-3"><Info icon={<Search size={17}/>} title="Search" text="Find someone by their unique username."/><Info icon={<Send size={17}/>} title="Request" text="Send a connection request before messaging."/><Info icon={<ShieldCheck size={17}/>} title="Private" text="Gmail identity stays separate from your public Anvaya ID."/></div></div></div>
}
function Avatar({profile}){const [broken,setBroken]=useState(false);const fallback=(profile?.display_name||profile?.username||"A").slice(0,1).toUpperCase();return profile?.avatar_url&&!broken?<img alt="" src={profile.avatar_url} onError={()=>setBroken(true)} className="h-12 w-12 rounded-full object-cover"/>:<div className="h-12 w-12 rounded-full bg-gradient-to-br from-[#123f33] to-[#18382f] grid place-items-center text-lg font-semibold text-emerald-100">{fallback}</div>}
function Info({icon,title,text}){return <div className="rounded-2xl border border-white/[.06] bg-white/[.02] p-4"><div className="text-aurora-300 mb-3">{icon}</div><div className="font-medium text-sm">{title}</div><div className="text-xs text-white/30 mt-1 leading-5">{text}</div></div>}
