import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, Bell, CalendarDays, CheckCircle2, CircleDollarSign, Clock3, CloudSun, CreditCard, Download, FileText, FolderLock, Globe2, ListChecks, MoreHorizontal, Pencil, Plus, Receipt, Search, ShieldCheck, Sparkles, Trash2, UploadCloud, Users, WalletCards, X } from "lucide-react";
import { api } from "../lib/api";
import { supabase } from "../lib/supabase";

const KEY={notes:"vyara_notes",expenses:"vyara_expenses",subs:"vyara_subscriptions",events:"vyara_events",vault:"vyara_vault"};
const scopedKey=(k,userId)=>`${k}_${userId}`;
const LEGACY_DEMO_IDS=new Set([1,2,3,4,5]);
const load=(k,userId,f)=>{try{const x=JSON.parse(localStorage.getItem(scopedKey(k,userId)));if(!Array.isArray(x))return f;const cleaned=x.filter(item=>!LEGACY_DEMO_IDS.has(item?.id));if(cleaned.length!==x.length)localStorage.setItem(scopedKey(k,userId),JSON.stringify(cleaned));return cleaned}catch{return f}};
const save=(k,userId,v)=>{localStorage.setItem(scopedKey(k,userId),JSON.stringify(v));window.dispatchEvent(new CustomEvent("vyara:data-changed",{detail:{key:k,userId}}));};

export function Pages({page,onNavigate,enabled,setEnabled,model,setModel,user}){
  const userId=user?.id||"local";
  switch(page){
    case "Command Center": return <CommandCenter onNavigate={onNavigate} userId={userId}/>;
    case "Chats": return <div className="h-full grid place-items-center p-8"><div className="glass rounded-3xl p-8 max-w-md text-center"><Sparkles className="mx-auto text-aurora-300" size={28}/><h2 className="text-xl font-semibold mt-4">Your conversations are ready</h2><p className="text-sm text-white/35 mt-2">Open Chats from the sidebar to message people. Astra can be invited from any conversation.</p><button className="btn-primary mt-5" onClick={()=>onNavigate("Chats")}>Open Chats</button></div></div>;
    case "Notes": return <Notes userId={userId}/>;
    case "Money": return <Money userId={userId}/>;
    case "Subscriptions": return <Subscriptions userId={userId}/>;
    case "Anvaya Vault": return <Vault userId={userId}/>;
    case "Calendar": return <Calendar userId={userId}/>;
    case "World": return <World/>;
    case "Privacy Center": return <Privacy/>;
    case "Settings": return <Settings enabled={enabled} setEnabled={setEnabled} model={model} setModel={setModel} user={user}/>;
    default:return <CommandCenter onNavigate={onNavigate}/>;
  }
}

function LiveDateTime(){
  const [now,setNow]=useState(()=>new Date());
  useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
  const date=new Intl.DateTimeFormat(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now);
  const time=new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit",second:"2-digit",hour12:true}).format(now);
  return <div className="rounded-2xl border border-white/[.06] bg-white/[.025] px-4 py-3 min-w-[210px]"><div className="text-xs text-white/35">Today</div><div className="text-sm mt-1">{date}</div><div className="text-xl font-semibold mt-1 text-emerald-200">{time}</div></div>;
}

export function CommandCenter({onNavigate,userId}){
  const read=()=>({notes:load(KEY.notes,userId,[]),expenses:load(KEY.expenses,userId,[]),subs:load(KEY.subs,userId,[]),events:load(KEY.events,userId,[]),vault:load(KEY.vault,userId,[])});
  const [data,setData]=useState(read);
  useEffect(()=>{const refresh=()=>setData(read());window.addEventListener("vyara:data-changed",refresh);window.addEventListener("storage",refresh);const timer=setInterval(refresh,1000);return()=>{window.removeEventListener("vyara:data-changed",refresh);window.removeEventListener("storage",refresh);clearInterval(timer)}},[userId]);
  const total=data.expenses.reduce((a,e)=>a+Number(e.amount||0),0);
  const owedTotal=data.expenses.reduce((a,e)=>a+Number(e.owed||0),0);
  const payments=data.events.filter(e=>e.type==="Payment");
  const upcomingPayments=payments.reduce((a,e)=>a+parseAmount(e.time),0);
  const birthday=data.events.find(e=>e.type==="Birthday");
  const payment=payments[0];
  const owed=data.expenses.find(e=>Number(e.owed||0)>0);
  const activities=[...data.events.map(e=>({text:`${e.title} added to Calendar`,time:e.date||"Upcoming",sort:e.id||0})),...data.subs.map(s=>({text:`${s.name} subscription · ₹${Number(s.amount||0).toLocaleString("en-IN")}`,time:s.due||"Subscription",sort:s.id||0})),...data.notes.map(n=>({text:`${n.title} note saved`,time:"Notes",sort:n.id||0})),...data.vault.map(f=>({text:`${f.name} saved to Anvaya Vault`,time:"Vault",sort:f.id||0})),...data.expenses.map(e=>({text:`${e.name} expense · ₹${Number(e.amount||0).toLocaleString("en-IN")}`,time:"Money",sort:e.id||0}))].sort((a,b)=>Number(b.sort)-Number(a.sort)).slice(0,5);
  const empty=!data.notes.length&&!data.expenses.length&&!data.subs.length&&!data.events.length&&!data.vault.length;
  return <PageShell title="Command Center" subtitle="Only what you add to Anvaya appears here." action={<div className="flex items-center gap-2"><LiveDateTime/><button onClick={()=>onNavigate("Chats")} className="btn-primary"><Sparkles size={15}/> Open chats</button></div>}>
    <div className="grid grid-cols-12 gap-4">
      <Card className="col-span-12 lg:col-span-8 hero-card"><div className="flex items-start justify-between"><div><Pill icon={Activity} text="Live overview"/><h2 className="text-2xl sm:text-3xl font-semibold mt-4">Your Anvaya,<br/><span className="text-aurora-300">without the noise.</span></h2><p className="text-sm text-white/35 mt-3 max-w-xl">This view is built from your own Notes, Money, Calendar, Subscriptions and Vault data. Nothing is pre-filled.</p></div><div className="hidden sm:grid h-14 w-14 rounded-2xl bg-white/[.05] place-items-center border border-white/[.06]"><Sparkles className="text-aurora-300" size={22}/></div></div>
        <div className="grid sm:grid-cols-3 gap-3 mt-7">
          <Attention title={birthday?.title||"No birthday reminders"} value={birthday?.date||"Add in Calendar"} icon={Bell}/>
          <Attention title={payment?.title||"No upcoming payments"} value={payment?.time||"Add a payment"} icon={CreditCard}/>
          <Attention title={owed?`${owed.name} owes you`:"No balances yet"} value={owed?`₹${Number(owed.owed).toLocaleString("en-IN")}`:"Add a balance in Money"} icon={WalletCards}/>
        </div>
      </Card>
      <Card className="col-span-12 lg:col-span-4"><SectionTitle title="Astra AI" icon={Sparkles}/><div className="rounded-2xl bg-gradient-to-br from-[#3b1628] to-[#20162f] p-5 border border-white/[.06]"><div className="text-lg font-medium">Intelligence on your terms.</div><p className="text-xs text-white/35 leading-5 mt-2">Ask Astra about your work without making AI the default.</p><div className="mt-4 text-[10px] text-emerald-300">● Ready when invited</div></div></Card>
      <Metric title="This month's spend" value={`₹${total.toLocaleString("en-IN")}`} note={data.expenses.length?"Synced from Money":"No expenses yet"} icon={CircleDollarSign} trend={data.expenses.length>0?"down":null}/>
      <Metric title="Upcoming payments" value={`₹${upcomingPayments.toLocaleString("en-IN")}`} note={payments.length?`${payments.length} payment${payments.length===1?"":"s"} in Calendar`:"No payments yet"} icon={CalendarDays}/>
      <Metric title="Active subscriptions" value={String(data.subs.length)} note={data.subs.length?`${data.subs.length} saved in Subscriptions`:"No subscriptions yet"} icon={Receipt}/>
      <Card className="col-span-12 lg:col-span-8"><SectionTitle title="Recent activity" icon={Clock3}/>{activities.length?activities.map((x,i)=><ActivityRow key={`${x.text}-${i}`} text={x.text} time={x.time}/>):<div className="py-8 text-sm text-white/25">Nothing here yet. Add something in Notes, Money, Calendar, Subscriptions or Vault.</div>}</Card>
      <Card className="col-span-12 lg:col-span-4"><SectionTitle title="Your day" icon={Clock3}/><LiveDateTime/><div className="mt-4 text-xs text-white/30">{empty?"Start adding the things you actually use and they will appear here automatically.":`${data.events.length} calendar item${data.events.length===1?"":"s"} · ${data.notes.length} note${data.notes.length===1?"":"s"} · ${data.vault.length} vault file${data.vault.length===1?"":"s"}`}</div></Card>
    </div>
  </PageShell>
}
function parseAmount(value){const n=String(value||"").replace(/[^0-9.]/g,"");return Number(n)||0}

export function Notes({userId}){const [notes,setNotes]=useState(()=>load(KEY.notes,userId,[]));const [editing,setEditing]=useState(null);useEffect(()=>save(KEY.notes,userId,notes),[notes,userId]);
 function add(){setEditing({id:Date.now(),title:"",tag:"PERSONAL",body:""})} function commit(){if(!editing?.title.trim())return;setNotes(n=>n.some(x=>x.id===editing.id)?n.map(x=>x.id===editing.id?editing:x):[editing,...n]);setEditing(null)}
 return <PageShell title="Notes" subtitle="A quiet place for thoughts, plans and things worth keeping." action={<button className="btn-primary" onClick={add}><Plus size={15}/> New note</button>}><div className="notes-grid">{notes.map((n,i)=><article key={n.id} className={`note-card note-${(i%4)+1}`}><div className="flex items-center justify-between"><span className="note-tag">{n.tag}</span><button onClick={()=>setEditing(n)}><MoreHorizontal size={16} className="text-white/25"/></button></div><h3 className="text-xl font-medium mt-8">{n.title}</h3><p className="text-sm text-white/35 leading-6 mt-3">{n.body}</p><div className="mt-8 text-[10px] text-white/20">Saved locally · editable</div></article>)}</div>{editing&&<Editor title={editing.id&&notes.some(n=>n.id===editing.id)?"Edit note":"New note"} onClose={()=>setEditing(null)} onSave={commit}><input className="form-input" autoFocus value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder="Note title"/><select className="form-input" value={editing.tag} onChange={e=>setEditing({...editing,tag:e.target.value})}><option>PERSONAL</option><option>WORK</option><option>TRAVEL</option><option>AI</option></select><textarea className="form-input min-h-32" value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})} placeholder="Write something…"/></Editor>}</PageShell>}

export function Money({userId}){
  const [expenses,setExpenses]=useState(()=>load(KEY.expenses,userId,[]));
  const [open,setOpen]=useState(false);
  const [editingOwed,setEditingOwed]=useState(null);
  useEffect(()=>save(KEY.expenses,userId,expenses),[expenses,userId]);
  const total=expenses.reduce((a,e)=>a+Number(e.amount||0),0);
  const owedRows=expenses.filter(e=>Number(e.owed||0)>0);
  const owedTotal=owedRows.reduce((a,e)=>a+Number(e.owed||0),0);
  function add(e){e.preventDefault();const f=new FormData(e.currentTarget);setExpenses(x=>[{id:Date.now(),name:f.get("name"),amount:Number(f.get("amount")),owed:Number(f.get("owed")||0)},...x]);setOpen(false)}
  function updateOwed(e){e.preventDefault();const f=new FormData(e.currentTarget);setExpenses(x=>x.map(item=>item.id===editingOwed.id?{...item,owed:Number(f.get("owed")||0),name:f.get("name")||item.name}:item));setEditingOwed(null)}
  return <PageShell title="Money" subtitle="See spending, balances and obligations without the spreadsheet feel." action={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={15}/> Add expense</button>}>
    <div className="grid grid-cols-12 gap-4">
      <Card className="col-span-12 lg:col-span-7 money-hero"><div className="flex justify-between"><div><div className="text-xs text-white/30">September spending</div><div className="text-4xl font-semibold mt-2">₹{total.toLocaleString("en-IN")}</div><div className="flex items-center gap-1 text-xs text-emerald-300 mt-2"><ArrowDownRight size={13}/> synced to Command Center</div></div><div className="money-ring"><span>74%</span><small>budget</small></div></div><div className="mt-8 h-2 rounded-full bg-white/[.06] overflow-hidden"><div className="h-full w-[74%] bg-gradient-to-r from-[#9c3157] to-[#70407e] rounded-full"/></div></Card>
      <Card className="col-span-12 sm:col-span-6 lg:col-span-5"><div className="flex items-center justify-between"><SectionTitle title="You are owed" icon={Users}/><button className="icon-btn !h-8 !w-8" title="Add balance" onClick={()=>setOpen(true)}><Plus size={14}/></button></div><div className="text-3xl font-semibold">₹{owedTotal.toLocaleString("en-IN")}</div><p className="text-xs text-white/30 mt-1">Across {owedRows.length} {owedRows.length===1?"person":"people"}</p><div className="mt-5 space-y-3">{owedRows.length?owedRows.map(item=><div key={item.id} className="flex items-center gap-2"><Balance name={item.name} amount={`₹${Number(item.owed).toLocaleString("en-IN")}`}/><button onClick={()=>setEditingOwed(item)} className="icon-btn !h-8 !w-8 ml-2" title="Edit"><Pencil size={13}/></button><button onClick={()=>setExpenses(x=>x.map(e=>e.id===item.id?{...e,owed:0}:e))} className="icon-btn !h-8 !w-8" title="Mark settled"><CheckCircle2 size={14}/></button></div>):<div className="text-xs text-white/25 py-3">No one owes you yet. Add a balance from an expense.</div>}</div></Card>
      <Card className="col-span-12"><SectionTitle title="Recent expenses" icon={Receipt}/>{expenses.map((x,i)=><div key={x.id} className="flex items-center gap-3 py-4 border-b border-white/[.04] last:border-0"><div className="h-9 w-9 rounded-xl bg-white/[.04] grid place-items-center"><CircleDollarSign size={16} className="text-white/40"/></div><div className="flex-1"><div className="text-sm">{x.name}</div><div className="text-[10px] text-white/25">{i===0?"Just now":`${i} day${i===1?"":"s"} ago`}{Number(x.owed||0)>0?` · ₹${Number(x.owed).toLocaleString("en-IN")} owed`:""}</div></div><div className="text-sm">₹{Number(x.amount).toLocaleString("en-IN")}</div><button onClick={()=>setExpenses(es=>es.filter(e=>e.id!==x.id))} title="Delete"><Trash2 size={15} className="text-white/20 hover:text-red-300"/></button></div>)}</Card>
    </div>
    {open&&<Editor title="Add expense" onClose={()=>setOpen(false)} form onSubmit={add}><input name="name" className="form-input" placeholder="Expense name" required/><input name="amount" type="number" min="0" step="1" className="form-input" placeholder="Amount ₹" required/><input name="owed" type="number" min="0" step="1" className="form-input" placeholder="Amount owed to you ₹ (optional)"/><button className="btn-primary w-full">Add expense</button></Editor>}
    {editingOwed&&<Editor title="Edit balance" onClose={()=>setEditingOwed(null)} form onSubmit={updateOwed}><input name="name" className="form-input" value={editingOwed.name} onChange={e=>setEditingOwed({...editingOwed,name:e.target.value})} placeholder="Person" required/><input name="owed" type="number" min="0" step="1" className="form-input" defaultValue={editingOwed.owed} placeholder="Amount owed ₹" required/><button className="btn-primary w-full">Save balance</button></Editor>}
  </PageShell>
}

export function Subscriptions({userId}){const [subs,setSubs]=useState(()=>load(KEY.subs,userId,[]));const [open,setOpen]=useState(false);useEffect(()=>save(KEY.subs,userId,subs),[subs,userId]);const monthly=subs.reduce((a,s)=>a+Number(s.amount||0),0);function add(e){e.preventDefault();const f=new FormData(e.currentTarget);setSubs(x=>[{id:Date.now(),name:f.get("name"),amount:Number(f.get("amount")),due:f.get("due")||"Next month",cat:f.get("cat")||"Other"},...x]);setOpen(false)}return <PageShell title="Subscriptions" subtitle="Know what renews, what it costs and what you actually use." action={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={15}/> Add subscription</button>}><div className="grid grid-cols-12 gap-4"><Card className="col-span-12 lg:col-span-4"><div className="text-xs text-white/30">Monthly commitment</div><div className="text-4xl font-semibold mt-2">₹{monthly.toLocaleString("en-IN")}</div><div className="text-xs text-white/30 mt-1">₹{(monthly*12).toLocaleString("en-IN")} estimated yearly</div><div className="mt-7 rounded-2xl bg-white/[.03] p-4"><div className="flex justify-between text-xs"><span className="text-white/35">Active subscriptions</span><b>{subs.length}</b></div><div className="flex justify-between text-xs mt-3"><span className="text-white/35">Highest subscription</span><b>{subs.reduce((best,s)=>!best||s.amount>best.amount?s:best,null)?.name||"—"}</b></div></div></Card><Card className="col-span-12 lg:col-span-8"><SectionTitle title="Your subscriptions" icon={Receipt}/>{subs.map(s=><div key={s.id} className="sub-row"><div className="sub-logo">{s.name[0]}</div><div className="flex-1"><div className="text-sm font-medium">{s.name}</div><div className="text-[10px] text-white/25 mt-1">{s.cat} · renews {s.due}</div></div><div className="text-sm">₹{Number(s.amount).toLocaleString("en-IN")}/mo</div><button onClick={()=>setSubs(x=>x.filter(a=>a.id!==s.id))}><Trash2 size={15} className="text-white/20 hover:text-red-300"/></button></div>)}</Card></div>{open&&<Editor title="Add subscription" onClose={()=>setOpen(false)} form onSubmit={add}><input name="name" className="form-input" placeholder="Service name" required/><input name="amount" type="number" min="0" className="form-input" placeholder="Monthly amount ₹" required/><input name="due" className="form-input" placeholder="Renewal date / text"/><input name="cat" className="form-input" placeholder="Category"/><button className="btn-primary w-full">Add subscription</button></Editor>}</PageShell>}

const vaultDbs=new Map();
function getVaultDb(userId){
  if(!userId || typeof indexedDB==="undefined") return null;
  if(vaultDbs.has(userId)) return vaultDbs.get(userId);
  const dbp=new Promise((res,rej)=>{
    const r=indexedDB.open(`vyara_vault_files_${userId}`,1);
    r.onupgradeneeded=()=>r.result.createObjectStore("files");
    r.onsuccess=()=>res(r.result);
    r.onerror=()=>rej(r.error);
  });
  vaultDbs.set(userId,dbp);
  return dbp;
}
const vaultDb={
  put:async(userId,id,file)=>{const dbp=getVaultDb(userId);if(!dbp)return;const d=await dbp;return new Promise((res,rej)=>{const t=d.transaction("files","readwrite");t.objectStore("files").put(file,id);t.oncomplete=res;t.onerror=()=>rej(t.error)})},
  get:async(userId,id)=>{const dbp=getVaultDb(userId);if(!dbp)return null;const d=await dbp;return new Promise((res,rej)=>{const t=d.transaction("files");const r=t.objectStore("files").get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})},
  del:async(userId,id)=>{const dbp=getVaultDb(userId);if(!dbp)return;const d=await dbp;return new Promise((res,rej)=>{const t=d.transaction("files","readwrite");t.objectStore("files").delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
};
export function Vault({userId}){const [files,setFiles]=useState(()=>load(KEY.vault,userId,[]));const [search,setSearch]=useState("");useEffect(()=>save(KEY.vault,userId,files),[files,userId]);async function upload(e){const fs=[...e.target.files||[]];for(const f of fs.filter(f=>f.size<=15*1024*1024)){const id=Date.now()+Math.random();if(vaultDb)await vaultDb.put(userId,id,f);setFiles(x=>[{id,name:f.name,size:formatBytes(f.size),type:f.type.startsWith("image/")?"IMAGE":f.name.split(".").pop()?.toUpperCase()||"FILE"},...x])}e.target.value=""}async function downloadFile(f){if(!vaultDb)return;const blob=await vaultDb.get(userId,f.id);if(!blob){alert("This older demo file has no local file data. Upload it again to enable download.");return}const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=f.name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}async function removeFile(id){if(vaultDb)await vaultDb.del(userId,id);setFiles(x=>x.filter(a=>a.id!==id))}const shown=files.filter(f=>f.name.toLowerCase().includes(search.toLowerCase()));return <PageShell title="Anvaya Vault" subtitle="Private files, separated from the noise of your conversations." action={<label className="btn-primary cursor-pointer"><UploadCloud size={15}/> <span>Upload</span><input type="file" multiple onChange={upload} className="hidden"/></label>}><div className="vault-banner"><div><div className="flex items-center gap-2 text-sm font-medium"><FolderLock size={16} className="text-emerald-300"/><span>Private storage</span></div><p className="text-xs text-white/30 mt-2">Files stay in this browser for the prototype. Download is available for files uploaded in this browser.</p></div><div className="relative"><Search size={15} className="absolute left-3 top-2.5 text-white/25"/><input value={search} onChange={e=>setSearch(e.target.value)} className="search-input pl-9" placeholder="Search vault"/></div></div><div className="grid grid-cols-2 md:grid-cols-3 gap-4 mt-5">{shown.map(f=><div className="file-card" key={f.id}><div className="file-preview"><FileText size={34} className="text-white/25"/></div><div className="mt-3 text-sm truncate" title={f.name}>{f.name}</div><div className="flex items-center justify-between gap-2 text-[10px] text-white/25 mt-1"><span className="truncate">{f.type} · {f.size}</span><div className="flex items-center gap-1 shrink-0"><button onClick={()=>downloadFile(f)} title="Download" className="icon-btn !h-8 !w-8"><Download size={14}/></button><button onClick={()=>removeFile(f.id)} title="Delete" className="icon-btn !h-8 !w-8"><Trash2 size={14}/></button></div></div></div>)}</div></PageShell>}

export function Calendar({userId}){const [events,setEvents]=useState(()=>load(KEY.events,userId,[]));const [open,setOpen]=useState(false);useEffect(()=>save(KEY.events,userId,events),[events,userId]);function add(type){setOpen({type:titleCase(type),title:"",date:"",time:""})}function commit(e){e.preventDefault();const f=new FormData(e.currentTarget);setEvents(x=>[...x,{id:Date.now(),title:f.get("title"),date:f.get("date"),type:open.type,time:f.get("time")}]);setOpen(false)}return <PageShell title="Calendar" subtitle="Birthdays, payments, tasks and events in one timeline." action={<button className="btn-primary" onClick={()=>add("reminder")}><Plus size={15}/> Add reminder</button>}><div className="grid grid-cols-12 gap-4"><Card className="col-span-12 lg:col-span-8"><SectionTitle title="Upcoming" icon={CalendarDays}/>{events.map(e=><div className="calendar-row" key={e.id}><div className="date-chip"><b>{e.date?.split(" ")[1]||e.date?.slice(0,9)||"—"}</b><span>{e.date}</span></div><div className="flex-1"><div className="text-sm font-medium">{e.title}</div><div className="text-[10px] text-white/25 mt-1">{e.type}{e.time?` · ${e.time}`:""}</div></div><button onClick={()=>setEvents(x=>x.filter(a=>a.id!==e.id))} className="text-white/20 hover:text-red-300"><Trash2 size={15}/></button></div>)}</Card><Card className="col-span-12 lg:col-span-4"><SectionTitle title="Quick add" icon={ListChecks}/>{["Birthday","Payment","Task","Event"].map(x=><button key={x} className="quick-add" onClick={()=>add(x)}><Plus size={15}/>{x}<span>⌘</span></button>)}</Card></div>{open&&<Editor title={`Add ${open.type}`} onClose={()=>setOpen(false)} form onSubmit={commit}><input name="title" className="form-input" placeholder="What should Anvaya remember?" required/><input name="date" className="form-input" placeholder="Date, e.g. Sep 18 or Oct 14" required/><input name="time" className="form-input" placeholder="Time / amount (optional)"/><button className="btn-primary w-full">Add reminder</button></Editor>}</PageShell>}

export function World(){const [city,setCity]=useState("Bengaluru"),[weather,setWeather]=useState(null),[loading,setLoading]=useState(false);async function load(){if(!city.trim())return;setLoading(true);try{setWeather(await api.weather(city))}catch(e){setWeather({error:e?.message||"Unable to load weather."})}finally{setLoading(false)}}return <PageShell title="World" subtitle="Local time and weather for the people and places you care about."><div className="flex gap-2 mb-5"><input value={city} onChange={e=>setCity(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} className="search-input w-64" placeholder="City"/><button onClick={load} className="btn-primary">{loading?"Loading…":"Get weather"}</button></div><div className="grid grid-cols-12 gap-4"><Card className="col-span-12 lg:col-span-4 world-main"><div className="text-sm text-white/35">Bengaluru</div><div className="text-5xl font-semibold mt-2">26°</div><div className="text-sm text-white/40 mt-2">Cloudy · 🇮🇳 IST</div></Card><Card className="col-span-12 lg:col-span-4"><div className="text-sm text-white/35">New York</div><div className="text-5xl font-semibold mt-2">21°</div><div className="text-sm text-white/40 mt-2">🇺🇸 EDT · 10:42 AM</div></Card><Card className="col-span-12 lg:col-span-4">{weather?.error?<div className="text-red-300 text-sm">{weather.error}</div>:weather?<><div className="text-sm text-white/35">{weather.city}</div><div className="text-5xl font-semibold mt-2">{Math.round(weather.temp)}°</div><div className="text-sm text-white/40 mt-2 capitalize">{weather.description}</div></>:<div className="text-sm text-white/35">Search a city to use OpenWeather.</div>}</Card></div></PageShell>}

export function Privacy(){return <PageShell title="Privacy Center" subtitle="Understand what Anvaya stores locally and what Astra can access."><div className="grid grid-cols-12 gap-4"><Card className="col-span-12 lg:col-span-7"><SectionTitle title="Protection" icon={ShieldCheck}/>{["Gmail identity · no phone number","Astra requests go through your Anvaya server","Profile picture is stored per account in private Supabase Storage","Vault files are local in this prototype"].map(x=><div className="privacy-row" key={x}><div className="status-orb"><CheckCircle2 size={20}/></div><div className="text-sm">{x}</div></div>)}</Card><Card className="col-span-12 lg:col-span-5"><SectionTitle title="Astra permissions" icon={Sparkles}/>{["Cloud AI only when enabled","You choose the model","Financial actions require confirmation","No silent external actions"].map(x=><div className="flex gap-3 py-3 border-b border-white/[.04] text-sm" key={x}><span className="h-2 w-2 rounded-full mt-2 bg-white/20"/>{x}</div>)}</Card></div></PageShell>}

export function Settings({enabled,setEnabled,model,setModel,user}){const [readReceipts,setReadReceipts]=useState(true),[lastSeen,setLastSeen]=useState(true),[privacyBusy,setPrivacyBusy]=useState(false);useEffect(()=>{if(!user?.id)return;supabase.from("profiles").select("read_receipts_enabled,last_seen_enabled").eq("user_id",user.id).maybeSingle().then(({data})=>{setReadReceipts(data?.read_receipts_enabled!==false);setLastSeen(data?.last_seen_enabled!==false)})},[user?.id]);async function savePrivacy(field,value,setter){setter(value);setPrivacyBusy(true);const {error}=await supabase.from("profiles").update({[field]:value}).eq("user_id",user.id);if(error)setter(!value);setPrivacyBusy(false)}return <PageShell title="Settings" subtitle="Make Anvaya feel like yours." ><div className="max-w-3xl space-y-4"><Card><SectionTitle title="Astra AI" icon={Sparkles}/><div className="setting-hero"><div className="astra-mark"><Sparkles size={17}/></div><div className="flex-1"><div className="text-sm font-medium">Astra intelligence</div><div className="text-xs text-white/30 mt-1">Cloud AI is optional and controlled by you.</div></div><button className={`toggle ${enabled?"on":""}`} onClick={()=>setEnabled(!enabled)}><span/></button></div><div className="mt-5"><label className="text-xs text-white/35">Astra model</label><select value={model} onChange={e=>setModel(e.target.value)} className="settings-select mt-2"><optgroup label="Antigravity">{ASTRA_MODELS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</optgroup></select><div className="text-[10px] text-white/20 mt-2">These are Anvaya's curated Antigravity labels. Provider credentials stay private on the server.</div></div></Card><Card><SectionTitle title="Chat privacy" icon={ShieldCheck}/><div className="setting-hero"><div className="flex-1"><div className="text-sm font-medium">Read receipts</div><div className="text-xs text-white/30 mt-1">Allow blue double ticks when you read messages.</div></div><button disabled={privacyBusy} className={`toggle ${readReceipts?"on":""}`} onClick={()=>savePrivacy("read_receipts_enabled",!readReceipts,setReadReceipts)}><span/></button></div><div className="setting-hero mt-3"><div className="flex-1"><div className="text-sm font-medium">Last seen</div><div className="text-xs text-white/30 mt-1">Allow contacts to see when you were last active.</div></div><button disabled={privacyBusy} className={`toggle ${lastSeen?"on":""}`} onClick={()=>savePrivacy("last_seen_enabled",!lastSeen,setLastSeen)}><span/></button></div></Card><Card><SectionTitle title="Identity" icon={ShieldCheck}/><div className="setting-list"><div><span>Product</span><b>Anvaya</b></div><div><span>Signature</span><b>by hash</b></div><div><span>Identity</span><b>Gmail only</b></div></div></Card></div></PageShell>}

export const ASTRA_MODELS=[
{id:"gemini-3-flash-preview",name:"Gemini 3 Flash"},{id:"gemini-3.1-flash-lite",name:"Gemini 3.1 Flash Lite"},{id:"gemini-3.5-flash",name:"Gemini 3.5 Flash"},{id:"gemini-3.5-flash-lite",name:"Gemini 3.5 Flash Lite"},{id:"gemini-3.5-transcribe",name:"Gemini 3.5 Transcribe"},{id:"gemini-3.6-flash",name:"Gemini 3.6 Flash"},{id:"gemini-3.7-flash",name:"Gemini 3.7 Flash"},{id:"gemini-3.8-flash",name:"Gemini 3.8 Flash"},{id:"gemma-4-31b-it",name:"Gemma 4 31B"}];

function PageShell({title,subtitle,action,children}){return <div className="h-full overflow-auto scrollbar p-7"><div className="max-w-6xl mx-auto"><div className="mb-7 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="text-sm text-white/30 mt-1">{subtitle}</p></div>{action}</div>{children}</div></div>}
function Card({children,className=""}){return <div className={`panel rounded-2xl p-5 ${className}`}>{children}</div>}
function SectionTitle({title,icon:I}){return <div className="flex items-center gap-2 mb-5"><I size={16} className="text-aurora-300"/><span className="text-sm font-medium">{title}</span></div>}
function Pill({icon:I,text}){return <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/[.04] border border-white/[.06] text-xs text-white/45"><I size={13}/>{text}</span>}
function Attention({title,value,icon:I}){return <div className="attention"><I size={16} className="text-aurora-300"/><div className="text-sm mt-4">{title}</div><div className="text-xs text-white/30 mt-1">{value}</div></div>}
function Metric({title,value,note,icon:I,trend}){return <Card className="col-span-12 sm:col-span-4"><SectionTitle title={title} icon={I}/><div className="text-2xl font-semibold">{value}</div><div className={`text-xs mt-1 ${trend?"text-emerald-300":"text-white/25"}`}>{trend?<ArrowDownRight size={12} className="inline"/>:null}{note}</div></Card>}
function ActivityRow({text,time}){return <div className="flex items-center gap-3 py-3 border-b border-white/[.04] last:border-0 text-sm"><span className="h-2 w-2 rounded-full bg-aurora-500"/><span className="text-white/55">{text}</span><span className="ml-auto text-[10px] text-white/20">{time}</span></div>}
function WorldRow({city,temp,detail}){return <div className="flex items-center justify-between py-3 border-b border-white/[.04]"><div><div className="text-sm">{city}</div><div className="text-[10px] text-white/25 mt-1">{detail}</div></div><b>{temp}</b></div>}
function Balance({name,amount}){return <div className="flex justify-between text-sm"><span className="text-white/45">{name}</span><b>{amount}</b></div>}
function Editor({title,onClose,onSave,form=false,onSubmit,children}){return <div className="fixed inset-0 z-50 bg-black/65 backdrop-blur-md grid place-items-center p-4"><div className="w-full max-w-md glass rounded-3xl p-6"><div className="flex items-center justify-between mb-5"><div className="font-semibold">{title}</div><button onClick={onClose} className="icon-btn"><X size={16}/></button></div>{form?<form onSubmit={onSubmit} className="space-y-3">{children}</form>:<div className="space-y-3">{children}<button onClick={onSave} className="btn-primary w-full">Save</button></div>}</div></div>}
function formatBytes(n){if(n<1024)return `${n} B`;if(n<1024**2)return `${Math.round(n/1024)} KB`;return `${(n/1024**2).toFixed(1)} MB`}
function titleCase(s){return s.charAt(0).toUpperCase()+s.slice(1).toLowerCase()}
